### ISSUE TITLE
dilation convolution and two-stage strategy

### ISSUE THREAD

**Issue by leayz-888** [FengLi-ust/DN-DETR#25]
Thanks for your great work,
In your pre-trained model DN-DAB-Deformable-DETR-R50-v24, you did not use dilation convolution and two-stage strategy, what I want to know is, if using these two strategies can further improve the performance?
Looking forward to your reply!

**Comment by FengLi-ust** [comment]
Hi, we did not test them. I think these two strategies are more likely to further improve the performance. Thank you.

**Comment by leayz-888** [comment]
> Hi, we did not test them. I think these two strategies are more likely to further improve the performance. Thank you.

ok,thanks
