### ISSUE TITLE
How class embedding is implemented？

### ISSUE THREAD

**Issue by JianqiuChen** [FengLi-ust/DN-DETR#3]
Thanks for your excellent work.
Could you give more details how decoder embedding is specified as class label embedding？

**Comment by FengLi-ust** [comment]
You can refer to [Conditional DETR](https://arxiv.org/abs/2108.06152) or [DAB DETR](https://arxiv.org/abs/2201.12329), in which decoder queries are specified as a content part and a positional part. Therefore, we can set decoder content embedding as class label embedding as they are both related to content features.  Please feel free to ask any question that helps you understand this paper. Thank you.

**Comment by JianqiuChen** [comment]
Thanks for your reply. I have two questions about this part. How the class label embedding specifies to a class label? Is label noising  implementing for the content part of query?

**Comment by FengLi-ust** [comment]
Yes, label noising is implemented for the content part. For the first question, you can use label embedding to embed a class label, just like word embedding in NLP. Thank you.

**Comment by JianqiuChen** [comment]
Thank you, It inspires me a lot.

**Comment by encounter1997** [comment]
> You can refer to [Conditional DETR](https://arxiv.org/abs/2108.06152) or [DAB DETR](https://arxiv.org/abs/2201.12329), in which decoder queries are specified as a content part and a positional part. Therefore, we can set decoder content embedding as class label embedding as they are both related to content features. Please feel free to ask any question that helps you understand this paper. Thank you.

Hi, thanks for the amazing work! 
May I ask where does the "class label embedding" comes from?
To my understanding, the weight of each class in the classifier (for final prediction) is used to initialize the content embedding of corresponding ground-truth class (for denoising input). Is that right?

**Comment by FengLi-ust** [comment]
No. We add a new linear layer to embed the class labels.

**Comment by encounter1997** [comment]
> No. We add a new linear layer to embed the class labels.

OK, I get it. Thanks for your explanation~
