### ISSUE TITLE
About Introducing DN to Faster R-CNN

### ISSUE THREAD

**Issue by Mr-Bigworth** [FengLi-ust/DN-DETR#49]
Excuse me, the paper (https://arxiv.org/abs/2203.01305) shows the DN training can also be used in Faster R-CNN, I wonder how to implement it, Thanks!

**Comment by FengLi-ust** [comment]
We will consider releasing this code in the future. The implementation is quite similar to DN-DETR, where we append additional GT-denoised queries to the head and train the model to reconstruct the GT.
