### ISSUE TITLE
How Known Labels Detection implemented？

### ISSUE THREAD

**Issue by fblogy** [FengLi-ust/DN-DETR#5]
Thanks for your excellent work.
Could you give more details how Known Labels Detection implemented？How do you let the decoder output all boxes of specific class c only using the label embedding of class c?

**Comment by SuperHenry2333** [comment]
You can output boxes from all classes and only select those from the known class.

**Comment by fblogy** [comment]
Are you replace the all unknown class embedding by label embedding of class c in the matching part ，and the number of times you need to inference is the number of classes in the image？

**Comment by SuperHenry2333** [comment]
Yes, your understanding is right.

**Comment by tzhhhh123** [comment]
Thanks for your excellent work.
May I ask about the specific implementation of the fine-tuning phase？
